### ISSUE TITLE
What is the intended data-binding pattern with simpleschema component collections?

### ISSUE THREAD

**Issue by 100ideas** [fabienb4/meteor-materialize-components#2]
Create fixtures to populate component collections as desired, then pass component docs into templates in helpers? 

or am I missing the bigger picture around dynamically creating the components and storing them in the collection. Is it for a frontend-design app?

**Comment by fabienb4** [comment]
Yeah, you can generate pages dynamically.

Think Wordpress, but instead of posts, it's whatever components you want to show up on your pages.

Here is a quick example of how it can be used:

``` js
var pageComponentSchema = new SimpleSchema({
  type:  { type: String, allowedValues: _.keys(Components) },
  _id:   { type: SimpleSchema.RegEx.Id },
  order: { type: Number }
});

var pageSchema = new SimpleSchema({
  name:       { type: String, index: true, unique: true },
  components: { type: [pageComponentSchema], optional: true },
  order:      { type: Number }
});
```

``` markdown
{{#each components}}
  {{> Template.dynamic template=componentTemplate data=componentData}}
{{/each}}
```

``` js
  components: function() {
    return _.sortBy(this.components, "order");
  },
  componentTemplate: function() {
    return Components[this.type].TEMPLATE;
  },
  componentData: function() {
    return Components[this.type].findOne(this._id);
  }
```

**Comment by 100ideas** [comment]
Cool, thanks for explaining. I am looking forward to seeing this package develop.

**Comment by 100ideas** [comment]
So are you envisioning a collection-based "store" for component state, similar in concept to how state is managed in react, but implemented purely in meteor w/ blaze & collections?
