### ISSUE TITLE
jquery can't find .modal-trigger elements from Template.modal.onRendered callback

### ISSUE THREAD

**Issue by 100ideas** [fabienb4/meteor-materialize-components#3]
Here's my setup:

``` html
<body>
  {{> layout}}
  {{> modal id='loginmodal' content='modalcontent'}}
</body>

<template name="layout">
  {{> navbar title=navtitle links=navlinks}}
  <div class="container hero">
    <div class="row">
      <div class="col m4 s12">col m4 s12</div>
      <div class="col m4 s12">{{> hello}}</div>
      <div class="col m4 s12">col m4 s12</div>
    </div>
  </div>
</template>
```

``` coffeescript
Template.layout.helpers
  navtitle: ->
    text: "go", link: "#"
  navlinks: ->
    console.log("main.coffee layout.helpers.navlinks")
    [
      options: href: "#"
      linkText: "link 1"
    ,
      options: 
        href: "#loginmodal"
        class: "waves-effect waves-light btn modal-trigger"
      linkText: "login/out"
    ]
```

Added `console.log()` calls to the navbar and [modal component template helpers](https://github.com/fabienb4/meteor-materialize-components/blob/master/components/basic/modal.js#L2) in the package source, like this:

``` javascript
Template.modal.onRendered(function() {
  console.log('fabienb4-modal onRendered; this.$(modal-trigger"):');
  console.dir(this.$(".modal-trigger"));
  this.$(".modal-trigger").leanModal();
});
```

result from javascript console:

```
main.coffee layout.helpers.navlinks
fabienb4-navbar onRendered
fabienb4-modal onRendered; this.$(modal-trigger"):
jQuery.fn.init[0]
```

executing `this.$(".modal-trigger").leanModal();` in the console after the page loads produces (note it finds two elements...??):

``` html
[<a href=​"#loginmodal" class=​"waves-effect waves-light btn modal-trigger">​…​</a>​, 
<a href=​"#loginmodal" class=​"waves-effect waves-light btn modal-trigger">​…​</a>​]
```

Afterwards, the modal trigger works.

Any idea why the Template.modal.onRendered callback is firing before the element with the `.modal-trigger` are ready? 

Are my templates nested in the wrong order?

**Comment by fabienb4** [comment]
Sorry about the stupid error, I made some changes right before committing, in the way triggers are handled, and forgot to change this...

The two elements are because you have one in the menu on top, and one in the sidebar menu for smaller screen.

**Comment by 100ideas** [comment]
Works perfectly now, thanks!
